### ISSUE TITLE
Изучение Passport JS для будущей реализации авторизации.

### ISSUE THREAD

**Issue by ZaurQoban** [xx3u/amal_backend#100]
**Конечный результат:**
Что нужно сделать

**План решения:**
Нужно изучить документацию http://www.passportjs.org/ и сопутствующие материалы (включая видео-уроки по теме) для использования в будущем в качестве основы функционала авторизации.

**Мотивация:**
Это нужно, в первую очередь, разработчику для осуществления одной из основополагающих функций проекта - авторизации пользователя.

**Критерии приемки:**
Полученные навыки будут задействованы в выполнении тикета по авторизации.

**Планируемое время работы:**
5 часов. Либо больше, либо меньше - в зависимости от скорости усвоения материала.

**Comment by BauyrjanSeidahmet** [comment]
Дата 05-06 августа 2021
Затраченное время: 3 часа
