### ISSUE TITLE
Реализовать обработку ошибок

### ISSUE THREAD

**Issue by OmegonAlpharius** [xx3u/amal_backend#11]
**Конечный результат:**
Все костомные ошибки стандартной структуры, для упрощения обработки на frontend

**План решения:**
https://dev.to/nedsoft/central-error-handling-in-express-3aej

**Мотивация:**
Зачем это нужно потребителю

**Критерии приемки:**
По каким критериям будет приниматься выполненная работа

**Планируемое время работы:**
1 час

**Comment by xx3u** [comment]
частичная реализация #130
