### ISSUE TITLE
Добавить валидацию запросов в приложение

### ISSUE THREAD

**Issue by OmegonAlpharius** [xx3u/amal_backend#21]
**Конечный результат:**
Обработка запросов и формирование и отправка ошибок однообразной структуры

**План решения:**
Как это сделать

**Мотивация:**
Для обработки ошибок на frontend`е

**Критерии приемки:**

**Планируемое время работы:**

**Comment by qwanysh** [comment]
попробуйте это решение: https://express-validator.github.io/docs/schema-validation.html
можно написать middleware, куда вы будете передавать нужную схему, по которой будет валидироваться входящий JSON
