### ISSUE TITLE
Связать Groups & Students

### ISSUE THREAD

**Issue by xx3u** [xx3u/amal_backend#22]
**Конечный результат:**
- Связать Groups & Students. 

**План решения:**
- Изучить документацию по реализации связей в Sequalize  https://sequelize.org/master/manual/assocs.html
- Реализовать связь между   Groups & Students  OneToMany
- Добавить migaration файл
- Добавить seed файл

**Мотивация:**
Необходим функционал добавления групп для выбранных студентов, у которых не было группы.

**Критерии приемки:**
Связь между Студентами и Группами.
Есть migartin
Есть seed
**Планируемое время работы:**
3 часа

**Comment by OmegonAlpharius** [comment]
При создании связи появилась проблема не переименовывалось  поле с fk как написано в документации
