### ISSUE TITLE
Реализовать бэкэнд для студентов

### ISSUE THREAD

**Issue by OmegonAlpharius** [xx3u/amal_backend#3]

**Comment by xx3u** [comment]
**Конечный результат:**
Создать бэкэнд для студентов

**План решения:**

1. Подключить eslint и airbnb style guide для проект. Добавить конфигурацию для .eslintrc файла.
2. Установить sequelize для PostgreSQL. Установить конфигурацию для файла .sequelizerc
3. Установить зависимости postgreSQL, sequelize
4. Инициализировать sequelize для установки шаблона структуры папок
5. Создание файла .env
6. Создание БД
7. Создание Модели
8. Рефакторинг migration файлов

**Мотивация:**
База студентов - приоритетная часть данных для заказчика

**Критерии приемки:**
По каким критериям будет приниматься выполненная работа

**Планируемое время работы:**
1 день
