### ISSUE TITLE
Баг при добавлении студентов - требует группу

### ISSUE THREAD

**Issue by ZaurQoban** [xx3u/amal_backend#55]
**Описание бага**
При добавлении нового студента, не осуществляет функционал, если поле "Группа" не заполнено, даже, если статус студента "Отчислен". При этом, данное поле не является обязательным. 

**Шаги воспроизведения:**
На фронте:
1) Зайти на страницу студентов;
2) Добавить нового студента;
3) Заполнить обязательные формы, оставив строку с Группой пустой;
4) Не добавляет студента, ссылается на ошибку в бэкенде. 

**Наблюдаемое поведение:**
При проверке на бэке через консоль лог, выдает ошибку кода 22P02. Текст гласит, что   original: error: invalid input syntax for type integer: ""

**Ожидаемое поведение:**
Функция добавления должна добавлять нового студента безотносительно наличия группы. Однако, добавление осуществляется, если группа в соответствующей форме выбрана.

**Причины:**
Отмечает, что поле с группой модели "Студент" не может принимать пустые значения.

**Вариант решения:**
Возможно, стоит отредактировать поле StreamId на предмет его обязательности.

**Comment by OmegonAlpharius** [comment]
Выполнен на frontend
https://github.com/xx3u/amal_frontend/pull/100
